spring.application.name=Chat

spring.config.import=classpath:common-application.properties

logging.level.org.hibernate.orm.mapping=DEBUG
logging.level.org.springframework=debug

server.port = 8081

spring.data.redis.host=localhost
spring.data.redis.port=6379

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/test?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=kko54855790@

jwt.secretKey=5gYvmuME7KapVEbRHn4qULcCfPaA00N5

