#spring:
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306.test?useSSL=false
#    username: root
#    password: kko54855790@
#  jpa:
#    database: mysql
#    database-platform: org.hibernate.dialect.MySQL8Dialect
#    generate-ddl: true
#    hibernate:
#      ddl-auto: update
#    show-sql: true
