spring.application.name=Chat
spring.config.import=classpath:application-common.properties
logging.level.org.hibernate.orm.mapping=DEBUG
logging.level.org.springframework=debug
server.port=8085
spring.data.redis.host="${REDIS_HOST}"
spring.data.redis.port="${REDIS_PORT}"
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

