spring.application.name=MemberService
server.port=8081
spring.profiles.active=local
spring.config.import=classpath:application-common.properties
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.oauth2.resource.servlet.OAuth2ResourceServerAutoConfiguration
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=${JWK_SET_URI:http://localhost:9000/oauth2/jwks}
spring.security.oauth2.resourceserver.jwt.jws-algorithms=HS384

#db config
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
#redis
spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=${REDIS_PORT:6379}
cloud.aws.credentials.access-key=${S3_ACCESSKEY}
cloud.aws.credentials.secret-key=${S3_SECRETKEY}
cloud.aws.s3.bucket.ocr=${S3_OCR_BUCKET}
cloud.aws.s3.bucket.board=${S3_BOARD_BUCKET}

# HikariCP 최적화
spring.datasource.hikari.maximum-pool-size=20
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.connection-timeout=3000
spring.datasource.hikari.idle-timeout=600000
spring.datasource.hikari.max-lifetime=1800000

# BCrypt strength
bcrypt.strength=6