spring:
  application:
    name: gateway

  cloud:
    gateway:
      # spring example
      spring:
        cloud:
          gateway:
            default-filters:
              - RemoveRequestHeader=Cookie
            routes:
              - id: user
                uri: lb://USER-SERVICE
                predicates:
                  - Path=/api/user/**

        security:
          oauth2:
            resourceserver:
              jwt:
                jwk-set-uri: http://api/user/jwks.json
