spring:

  application:
    name: gateway

  jwt:
    secret: ${JWT_KEY}

  security:
    oauth2:
      resourceserver:
        jwt:
          secret-key: ${JWT_KEY}

  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: user-service
              uri: http://localhost:8081
              predicates:
                - Path=/api/user/**,/api/auth/**
            - id: content-service
              uri: http://localhost:8082
              predicates:
                - Path=/api/notices/**,/api/groups/**/notices/**
            - id: chat-service
              uri: http://localhost:8083
              predicates:
                - Path=/api/chat/**
server:
  port: 8080

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.server: DEBUG
    org.springframework.security: DEBUG