spring:
  profiles:
    default: local

  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.oauth2.resource.servlet.OAuth2ResourceServerAutoConfiguration

  main:
    web-application-type: reactive

  config:
    import: classpath:application-common.properties

  cloud:
    gateway:
      server:
        webflux:
          default-filters:
            - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE

server:
  port: 8080

springdoc:
  swagger-ui:
    disable-swagger-default-url: true
    display-query-params-with-url: true
    urls:
      - name: Member Service
        url: /member-service/v3/api-docs
      - name: Content Service
        url: /content-service/v3/api-docs
  api-docs:
    enabled: true
