spring.application.name=ContentService
spring.config.import=classpath:common-application.properties
ocr.secretKey=${OCR_SECRETKEY}
ocr.apiUrl=${OCR_APIURL}
# JPA ??
spring.jpa.hibernate.ddl-auto=create
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
newsapi.clientId=${NEWSAPI_CLIENTID}
newsapi.clientSecret=${NEWSAPI_CLIENTSECRET}
server.port=8081
spring.elasticsearch.uris=http://localhost:9200