# Logging
logging.level.org.springframework.web=WARN
logging.level.org.springframework.security=WARN
logging.level.com.zaxxer.hikari=WARN
logging.level.org.springframework.jdbc.datasource=WARN
logging.level.org.springframework.data.mongodb.core.MongoTemplate=WARN
