spring.application.name=ContentService
server.port=8082
spring.profiles.default=local
spring.config.import=classpath:application-common.properties
ocr.secretKey=${OCR_SECRETKEY}
ocr.apiUrl=${OCR_APIURL}
# JPA ??
spring.jpa.hibernate.ddl-auto=create
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB
spring.data.mongodb.uri=${MONGODB_URI:mongodb://admin:0000@localhost:27017/curebridge-content-mongo?authSource=admin}
# optional - MongoDB ?? ??
spring.data.mongodb.database=curebridge-db
# logging (??)
openai.api-key=${OPENAI_API_KEY}
member.service.url=${MEMBER_SERVICE_URL}
#openai.ai-model=gpt-3.5-turbo
openai.ai-model=gpt-4o
newsapi.clientId=${NEWSAPI_CLIENTID}
newsapi.clientSecret=${NEWSAPI_CLIENTSECRET}
spring.elasticsearch.uris=${ELASTICSEARCH_URIS:http://localhost:9200}
elasticsearch.host=${ELASTICSEARCH_HOST}
elasticsearch.port=${ELASTICSEARCH_PORT}

#spring.jwt.secret=${JWT_KEY}
#??? ?? ????
spring.data.redis.host=${REDIS_HOST}
spring.data.redis.port=${REDIS_PORT}