spring.application.name=CommonModule
cloud.aws.s3.bucket.ocr=${S3_OCR_BUCKET}
cloud.aws.s3.bucket.board=${S3_BOARD_BUCKET}
spring.jwt.secret=${JWT_KEY}
cloud.aws.stack.auto=false
cloud.aws.region.static=ap-northeast-2
cloud.aws.credentials.access-key=${S3_ACCESSKEY}
cloud.aws.credentials.secret-key=${S3_SECRETKEY}
spring.data.redis.host=localhost
spring.data.redis.port=6379
